
local_lib=""

changeAuthor = getGroup() ?: CHANGE_AUTHOR
changeBranch = env.ghprbSourceBranch ?: CHANGE_BRANCH
changeTarget = env.ghprbTargetBranch ?: CHANGE_TARGET

repo = 'jenkins-pipeline-shared-libraries'

pipeline {
  agent {
    label 'rhel8 && !built-in'
  }

  stages {
    stage('Initialize') {
      steps {
        script {
          sh 'printenv'
          
          local_lib = library identifier: "local-lib@${changeBranch}", 
            retriever: modernSCM([$class: 'GitSCMSource', 
                                  remote: "https://github.com/${changeAuthor}/${repo}", 
                                  branches: "${changeBranch}", 
                                  credentialsId: 'kie-ci']), 
            changelog: false

          githubscm.checkoutIfExists(repo, changeAuthor, changeBranch, 'kiegroup', changeTarget, true)
        }
      }
    }

    stage('Test MavenCommand') {
      steps {
        script {
          local_lib.org.kie.jenkins.MavenCommand.new(this).withSettingsXmlId(maven.getSubmarineSettingsXmlId()).run('clean')
        }
      }
    }

    stage('Test Maven') {
      steps {
        script {
          maven.runMavenWithSettings(maven.getSubmarineSettingsXmlId(), 'clean', null)
        }
      }
    }

    stage('Test getRepositoryScm') {
      steps {
        script {
          def existingBranch = githubscm.getRepositoryScm(repo, changeAuthor, changeBranch)
          assert existingBranch != null

          def nonExistentBranch = githubscm.getRepositoryScm(repo, 'kiegroup', 'non-existent-branch')
          assert nonExistentBranch == null
        }
      }
    }
  }
  post {
    always {
      cleanWs()
    }
  }
}

/**
 *
 * @param projectUrl the github project url
 */
def getProject() {
    return (ghprbAuthorRepoGitUrl =~ /((git|ssh|http(s)?)|(git@[\w\.]+))(:(\/\/)?(github.com\/))([\w\.@\:\/\-~]+)(\.git)(\/)?/)[0][8]
}

/**
 *
 * @param projectUrl the github project url
 */
def getGroup() {
    return getProjectGroupName(getProject())[0]
}

/**
 * Returns an array containing group and name
 *
 * @param project the project
 * @param defaultGroup the default project group. Optional.
 */
def getProjectGroupName(String project, String defaultGroup = "kiegroup") {
    def projectNameGroup = project.split("\\/")
    def group = projectNameGroup.size() > 1 ? projectNameGroup[0] : defaultGroup
    def name = projectNameGroup.size() > 1 ? projectNameGroup[1] : project
    return [group, name]
}